// @flow
export const FETCH_UNIVERSITY_NAME_BEGIN: string =
  'FETCH_UNIVERSITY_NAME_BEGIN';
export const FETCH_UNIVERSITY_NAME_COMPLETE: string =
  'FETCH_UNIVERSITY_NAME_COMPLETE';
export const FETCH_UNIVERSITY_NAME_FAIL: string = 'FETCH_UNIVERSITY_NAME_FAIL';
